### ISSUE TITLE
Composite, orthogonal and submachine states: status and examples

### ISSUE THREAD

**Issue by mmikitka** [steelbreeze/state#1]
@mesmo Thank you for releasing your work.

Can you please comment on the status of composite, orthogonal and submachine states? For those state types that are implemented, might you be able to provide corresponding working examples in the "examples" folder?

Thank you

**Comment by mesmo** [comment]
Hi @mmikitka,

Any `State` within a model may be turned from a _simple_ state to a _composite_ state by adding sub-structure. This is done by creating a new `Region` and specifying it's parent as the state in question.

Creating a second _Region_ under the same parent state will turn it into an orthogonal state.

If you take a look at the tests there are many examples to pick from; I'm currently in the process of migrating the code over from another repository so more examples will be forthcoming soon.

Kind regards,
David.

**Comment by mmikitka** [comment]
Thank you for the helpful response, @mesmo
