### ISSUE TITLE
[feature request]deferred events support

### ISSUE THREAD

**Issue by redboltz** [steelbreeze/state#10]
Hi, thank you for writing the great library.
If state.js supports *deferred events*, it's more convenient.

Here is a document about deferred events that I wrote:
http://redboltz.wikidot.com/deferred-events

Deferred events functionality is a part of UML specification.

**Comment by mesmo** [comment]
Thanks for the feedback @redboltz, I'll look into it (it feels fairly straightforward, with one caveat of recognising the event type thanks to the delights of JavaScript).

**Comment by redboltz** [comment]
Thank you! I look forward to updates :)

**Comment by mesmo** [comment]
I have what I think is a good implementation of your first example in your document:
```typescript
import * as state from '../lib/node';

state.log.add((message: string) => console.info(message), state.log.Entry | state.log.Exit | state.log.Evaluate);

class Event1 { public constructor(public readonly name: string) { } public toString(): string { return this.name; } }
class Event2 { public constructor(public readonly name: string) { } public toString(): string { return this.name; } }

const model = new state.State("model");
const region = new state.Region("region", model);
const initial = new state.PseudoState("initial", region, state.PseudoStateKind.Initial);
const state1 = new state.State("state1", region);
const state2 = new state.State("state2", region);
const state3 = new state.State("state3", region);
const state4 = new state.State("state4", region);
const state5 = new state.State("state5", region);
const state6 = new state.State("state6", region);

state1.defer(Event1);
state2.defer(Event1);

initial.to(state1);
state1.to(state2).on(Event2);
state2.to(state3).on(Event2);
state3.to(state4).on(Event1);
state4.to(state5).on(Event1);
state5.to(state6).on(Event1);

let instance = new state.Instance("redboltz1", model);

instance.evaluate(new Event1("event1a"));
instance.evaluate(new Event1("event1b"));
instance.evaluate(new Event2("event2a"));
instance.evaluate(new Event2("event2b"));
```
I have added two new methods ```State.defer``` records the class of events to defer; ```Transition.on``` is a little unrelated to your enhancement request, but is something I'd wanted to do for a little while as it adds a class-based predicate to the transition evaluation criteria where I only had the guard condition previously.

The output is:
```
redboltz1 enter model
redboltz1 enter model.region
redboltz1 enter model.region.initial
redboltz1 leave model.region.initial
redboltz1 enter model.region.state1
redboltz1 evaluate event1a
redboltz1 defer event1a
redboltz1 evaluate event1b
redboltz1 defer event1b
redboltz1 evaluate event2a
redboltz1 leave model.region.state1
redboltz1 enter model.region.state2
redboltz1 evaluate event1a
redboltz1 defer event1a
redboltz1 evaluate event1b
redboltz1 defer event1b
redboltz1 evaluate event2b
redboltz1 leave model.region.state2
redboltz1 enter model.region.state3
redboltz1 evaluate event1a
redboltz1 leave model.region.state3
redboltz1 enter model.region.state4
redboltz1 evaluate event1b
redboltz1 leave model.region.state4
redboltz1 enter model.region.state5
```

**Comment by redboltz** [comment]
Thank you for the comment! The client code and the corresponding output look good to me.

**Comment by redboltz** [comment]
I noticed that a subtle point to implement deferred event.
Please see https://stackoverflow.com/questions/53390674/correct-order-of-deferred-events-in-state-machine-of-uml-2-x

**Comment by mesmo** [comment]
Hi, I've just run that through my current work-in-progress.

Source:
```typescript
import * as state from '../lib/node';

state.log.add((message: string) => console.info(message), state.log.Entry | state.log.Exit | state.log.Evaluate);

class e1 { public  toString(): string { return "e1"; } }
class e2 { public  toString(): string { return "e2"; } }
class e3 { public  toString(): string { return "e3"; } }
class e4 { public  toString(): string { return "e4"; } }

const model = new state.State("model");
const region = new state.Region("region", model);
const initial = new state.PseudoState("initial", region, state.PseudoStateKind.Initial);
const s1 = new state.State("s1", region);
const s2 = new state.State("s2", region);
const s3 = new state.State("s3", region);
const s4 = new state.State("s4", region);
const s5 = new state.State("s5", region);

s1.defer(e1);
s1.defer(e2);
s1.defer(e3);

s2.defer(e1);
s2.defer(e3);


initial.to(s1);
s1.to(s2).on(e4);
s2.to(s3).on(e2);
s3.to(s4).on(e1);
s3.to(s5).on(e3);

let instance = new state.Instance("redboltz3", model);

instance.evaluate(new e1());
instance.evaluate(new e2());
instance.evaluate(new e3());
instance.evaluate(new e4());
```
Producing:
```
redboltz3 enter model
redboltz3 enter model.region
redboltz3 enter model.region.initial
redboltz3 leave model.region.initial
redboltz3 enter model.region.s1
redboltz3 evaluate e1
redboltz3 defer e1
redboltz3 evaluate e2
redboltz3 defer e2
redboltz3 evaluate e3
redboltz3 defer e3
redboltz3 evaluate e4
redboltz3 leave model.region.s1
redboltz3 enter model.region.s2
redboltz3 evaluate e2
redboltz3 leave model.region.s2
redboltz3 enter model.region.s3
redboltz3 evaluate e1
redboltz3 leave model.region.s3
redboltz3 enter model.region.s4
redboltz3 evaluate e3
```

**Comment by redboltz** [comment]
Perfect!

**Comment by mesmo** [comment]
Code released under v7.1.0....

**Comment by redboltz** [comment]
Thank you very much!!

**Comment by redboltz** [comment]
I think that you mean the following case:

```
+---------------------+ event1  +--------------+
|  stateA             |-------->| stateB       |
|                     |         +--------------+
|  +-------------+    |
|  |stateAa      |    |
|  |event1/defer |    |
|  +-------------+    |
+---------------------+
```

`event1` should be deferred at `stateAa`, so no transition from `stateA` to `stateB` happened.

Events should be evaluated inside to outside.

Consider the following example:

```
+---------------------+ event1  +--------------+
|  stateA             |-------->| stateB       |
|                     |         +--------------+
|  +-------------+    |
|  |stateAa      |    |
|  |event1/act1  |    |
|  +-------------+    |
+---------------------+
```

In this case (the current state is stateAa), when event1 is processed, act1 is executed but the current state is still stateAa because event1 is **consumed** by act1.

Back to the original state-machine.

Please download formal-17-12-05.pdf via the link UML/2.5.1/PDF in https://www.omg.org/spec/UML/About-UML/.

14.2.3.9.3 Conflicting Transitions

> An internal Transition in a State conflicts only with Transitions that cause an exit from that State.

That means `event1` is NOT conflicted in the case.

By the way, what happened if conflict is occurred?

Please download ptc-17-04-04.pdf via the link PSSM/1.0/Beta1/PDF in https://www.omg.org/spec/PSSM/About-PSSM/.

See 9.3.16.3 Deferred 002 is conflicted case. The deferred transition is overridden by non-deferred transition.

9.3.16.5 Deferred 004-A is similar case as your case. If the deferred event would be overridden by parent state `S1`, transition `T3` would happen. But it doesn't happen.
So it supports my idea. But I don't understand why `S1.1`'s defer and `S2.2`'s `T2.2` don't happen parallel.

**Comment by mesmo** [comment]
Thanks, that's what I had hoped and I'll be updating my implementation soon to _consume_ the event on deferral.

> By the way, what happened if conflict is occurred?

When the guard conditions of multiple transitions from the same state evaluate true, I throw an exception.  My ```Instance``` class has a rudimentary form of transaction management in it so the active state configuration will not be updated if an exception is thrown either by my code or user-defined state entry/exit behaviour.

Both UML documents now in my library... (I had been working from the 2.4.1 documentation historically)

**Comment by redboltz** [comment]
As far as I can imagine, there is no meaningful reason to write conflicting transition. I think that throwing exception is better behavior than following UML spec.

**Comment by mesmo** [comment]
I'm yet to update the graphic and text on the page, but in [this example](https://steelbreeze.net/state/) the stopped state will defer the Play event.
