### ISSUE TITLE
visitElement return types and return values

### ISSUE THREAD

**Issue by mmikitka** [steelbreeze/state#2]
Can you help me reconcile the following:
* Visitor::visitElement returns *any* and has no implementation
* Runtime::visitElement returns *void*
* Visitor::{visitRegion, visitVertex, visitStateMachine} return *this.visitElement(...)*

**Comment by mesmo** [comment]
Hi @mmikitka 

> Visitor::visitElement returns any and has no implementation

The `Visitor` class is an abstract class from which other Visitors can be derived; it broadly follows the Visitor pattern. I needed one visitor (the `Runtime` class), but thought it best to add this as a point of extensibility. The logic inside `Visitor` just walks the state machine model calling the `Visitor::visit…` methods; these return any (and the logic in the base class propagates return values). If you choose to create a custom visitor then you may want to return values. Also take a look at the `accept` methods within rest of the code.

> Runtime::visitElement returns void

Within my implementation of `Runtime`, which is used to evaluate the structure of the model and effectively compile the state machine into a series of delegates, the bulk of what is happening does not require return values from the the `Runtime::visit…` methods (it’s an oversight of mine that some of the `Runtime::visit…` methods return `void` and some do not state a return type - now fixed). However you will see that `Runtime::visitStateMachine` which returns a `Delegate` which is used to initialise new state machine instances (see the `StateMachine.initialise` method).

> Visitor::{visitRegion, visitVertex, visitStateMachine} return this.visitElement(...)

To call a visitor you instantiate it and pass it to the `accept` method on any of the elements within a state machine model; the `accept` method will return the final result of the `visit…` method that it calls.

Probably worth checking out the Visitor pattern here: https://en.wikipedia.org/wiki/Visitor_pattern

**Comment by mmikitka** [comment]
Hi @mesmo,

I am familiar with the Visitor pattern; I was just trying to point out, albeit in a terse way, the following:

> it’s an oversight of mine that some of the Runtime::visit… methods return void and some do not state a return type - now fixed
