### ISSUE TITLE
Storing application state

### ISSUE THREAD

**Issue by mmikitka** [steelbreeze/state#3]
*Use case*: A multi-step form (potentially 100+ steps) which gathers information from a user (a type of Decision Support System, DSS). At each point in the multi-step form (state), I want to store the answers for use by a subsequent step (sibling state in the same region, or child state in a composite state region), or for the purpose of reloading previously-entered information into a form in the event that the user moves back in the decision-making process.

Can you recommend an approach for storing application state (not a snapshot of the FSM, but a snapshot of the application context) within a state machine instance? Does the following seem reasonable?

```typescript
export interface IInstance {
  ...
  setCurrentAppContext(vertex: Vertex, context: any): void;
  getCurrentAppContext(vertex: Vertex): any;
  ...
}
```
Thank you.

**Comment by mesmo** [comment]
If you're writing in TypeScript, I'd suggest you inherit from JSONInstance or DictionaryInstance and then make the additions you need to store your own application state (which will then be available easily for guard conditions and entry/exit/transition behaviour).
