### ISSUE TITLE
Second pass through state machine yields different results

### ISSUE THREAD

**Issue by mmikitka** [steelbreeze/state#4]
Given [this state machine](https://gist.github.com/mmikitka/6bcbd8243ca40e628b14a86f93d802d4), and the corresponding execution log at the end of this post:

* On the first pass, when "Continue" then "No" is processed, the instance moves into A_1.
* On the second pass, when "Continue" then "No" is processed, the instance moves into A_pass, when I expected it to move to A_1.

> initialise model
initialise instance
instance enter model.default
instance enter model.default.initial
instance leave model.default.initial
instance enter model.default.identify

>instance evaluate message: Continue
instance leave model.default.identify
instance enter model.default.exception_1

>instance evaluate message: No
instance leave model.default.exception_1
instance enter model.default.A
instance enter model.default.A.default
instance enter model.default.A.default.A_initial
instance leave model.default.A.default.A_initial
instance enter model.default.A.default.A_1

>instance evaluate message: Yes
instance leave model.default.A.default.A_1
instance enter model.default.A.default.A_2

>instance evaluate message: Yes
instance leave model.default.A.default.A_2
instance enter model.default.A.default.A_pass
instance leave model.default.A.default.A_pass
instance leave model.default.A.default
instance leave model.default.A
instance enter model.default.model_pass
instance leave model.default.model_pass
instance enter model.default.identify

>instance evaluate message: Continue
instance leave model.default.identify
instance enter model.default.exception_1

>instance evaluate message: No
instance leave model.default.exception_1
instance enter model.default.A
instance enter model.default.A.default
instance enter model.default.A.default.A_initial
instance leave model.default.A.default.A_initial
instance enter model.default.A.default.A_pass`

**Comment by mesmo** [comment]
Looks like a bug (some of the history semantics coming into play erroneously it would seem); will investigate and revert.

**Comment by mesmo** [comment]
Found and fixed (an error in Runtime::visitPseudoState that acted on history but without checking the model for history semantics) - thanks for the input.
