### ISSUE TITLE
Why a transition does not contain optional list of triggers?

### ISSUE THREAD

**Issue by jasonfreak** [steelbreeze/state#8]
Should I use the message to identify the event trigger? If yes, the guards become the same IFs and ELSEs that you wanted to eliminate by using the state machine in the first place.

**Comment by mesmo** [comment]
I'm not sure I fully understand the question, but here goes...

Each Vertex (State or PseudoState) can have multiple outbound transitions Each of these has a single guard condition that takes as parameters the state machine instance (where extended state variables can be maintained) and the object that is the triggering event as parameters; the guard is where you define the logic to determine if that transition should be followed or not. See the [Guard conditions section of the Wikipedia article on state machines](https://en.wikipedia.org/wiki/UML_state_machine#Guard_conditions).

So yes, in my example:
`stateA.to(stateB).when((instance, message) => message === "move");
`
message as the second parameter is the triggering event and I am just comparing to the string `"move"`; if you need more complex logic or use more structured triggers I would suggest you perform a type check as the first part of your guard condition as many different guard conditions may be tested for any given triggering event.

The value in using the state machine comes in when you have complex hierarchical state machine models, where the state machine library will perform a depth-first evaluation of triggering events based on the current state of the state machine instance. See the [Hierarchy and nested states section](https://en.wikipedia.org/wiki/UML_state_machine#Hierarchically_nested_states). Here, not only does it select the appropriate transition, but all the state exit and entry behaviour is triggered as needed; this is not necessarily only the source and destination states but can be much more complex a calculation. See the [Transition execution sequence section](https://en.wikipedia.org/wiki/UML_state_machine#Transition_execution_sequence).

**Comment by mesmo** [comment]
Hi @jasonfreak, thought you may be interested to know that in the latest version I now support event trigger type detection, so you can now write something like:
```
stateA.on(MyEvent).to(stateB)
```
Then subsequent calls to the ```when``` and ```do``` callbacks will be typed with MyEvent.
