### ISSUE TITLE
The FinalState removal could be added to the breaking changes list

### ISSUE THREAD

**Issue by fungiboletus** [steelbreeze/state#9]
Hei,
I am updating from state.js 5 to  @steelbreeze/state 7, following the breaking changes indications in the `RELEASES.md` file. Looking at the exception I have and the new examples, `FinalState` doesn't exist anymore.

This could be added to the breaking changes list.

**Comment by mesmo** [comment]
Thanks for the feedback, I've added this alongside the removal of the StateMachine class in item 1 in the list.
